version: '3.8'

services:
  mailgun-setup:
    image: ghcr.io/reclaimergold/mg2cf:latest
    # Uncomment to build from source instead:
    # build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-please-change-this-secret-key-in-production}
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment for resource limits:
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #       cpus: '0.5'
